version: "2"
linters:
  enable:
    - gocritic
    - misspell
    - unconvert
    - unparam
  settings:
    gocritic:
      enabled-checks:
        - nilValReturn
        - truncateCmp
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .heatmap
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 20
  max-same-issues: 5
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
